ui: tape

browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: internet explorer
    version: latest
  - name: MicrosoftEdge
    version: latest
  - name: opera
    version: latest
